# Dataset
dataset: &dataset !ImageNet2012Dataloader
  batch_size: 256

# Optimizers
optimizers: &optimizers
  weight_optimizer: 
    name: SGD
    params:
      lr: 0.05
      weight_decay: 0.00004
      momentum: 0.9
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 750750 # 5005 * 150

training_loop: &training_loop !TrainingLoop
  dataset: *dataset
  loss: !CrossEntropyLoss
  train_metrics:
    accuracy: !Accuracy
  val_metrics:
    accuracy: !Accuracy
  print_calibration: false

task: !Task
  training_loop: *training_loop
  optimizers: *optimizers
  model_arch: mobilenet_v2
  epochs: 150
  model_saver:
    monitor: "val_accuracy"
    mode: max
