model_parser: &model_parser !ModelParser
  wrappers:
    Conv2d: !QuantConv2d
      quantizer: !ModuleQuantizer
        input_quantizer: !StepOffsetQuantizer
          initializer: !MinErrorInitializer
          transformation: !Standardization
            momentum: 0.9999
            std_init: 1.0
        weight_quantizer: !StepQuantizer
          initializer: !MinErrorInitializer 
          transformation: !Standardization
            dim: [1, 2, 3]
          per_channel: true
      
    Linear: !QuantLinear
      quantizer: !ModuleQuantizer
        input_quantizer: !StepOffsetQuantizer
          initializer: !MinErrorInitializer
          transformation: !Standardization
            momentum: 0.9999
            std_init: 1.0
        weight_quantizer: !StepQuantizer
          initializer: !MinErrorInitializer 
          transformation: !Standardization
            dim: [1]
          per_channel: true

  input_bit_width:
    default: 3
    exceptions:
      conv1: 8
  weight_bit_width:
    default: 3
    exceptions:
      conv1: 8
  half_wave:
    default: true
    exceptions:
      conv1: false

# Dataset
dataset: &dataset !ImageNet2012Dataloader
  batch_size: 512

# Optimizers
optimizers: &optimizers
  weight_optimizer: 
    name: SGD
    model_params_type: weight
    params: 
      lr: 0.01
      weight_decay: 0.0001
      momentum: 0.9
      nesterov: false
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 225270
  quant_weight_optimizer: 
    name: Adam
    model_params_type: quant_weight
    params: 
      lr: 0.00001
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 225270
  quant_input_optimizer: 
    name: Adam
    model_params_type: quant_input
    params: 
      lr: 0.001
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 225270
  

training_loop: &training_loop !TrainingLoop
  dataset: *dataset
  loss: !CrossEntropyLoss
  train_metrics:
    accuracy: !Accuracy
  val_metrics:
    accuracy: !Accuracy

task: !Task
  training_loop: *training_loop
  epochs: 90
  model_parser: *model_parser
  optimizers: *optimizers
  model_saver:
    monitor: "val_accuracy"
    mode: max
  callbacks:
    - !QuantImagesCallback
