model_parser: &model_parser !ModelParser
    wrappers:
      Conv2d: !QuantConv2d
        quantizer: !ModuleQuantizer
          input_quantizer: !StepOffsetQuantizer
            initializer: !MinErrorInitializer
          weight_quantizer: !StepQuantizer
            initializer: !MeanStdInitializer
            per_channel: true

      Linear: !QuantLinear
        quantizer: !ModuleQuantizer
          input_quantizer: !StepOffsetQuantizer
            initializer: !MeanStdInitializer
          weight_quantizer: !StepQuantizer
            initializer: !MinErrorInitializer
            per_channel: true

    input_bit_width:
      default: 3
      exceptions:
        conv1: 8
    weight_bit_width:
      default: 3
      exceptions:
        conv1: 8
    half_wave:
      default: true
      exceptions:
        conv1: false

# Dataset
dataset: &dataset !ImageNet2012Dataloader
  batch_size: 512

# Optimizers
optimizers: &optimizers
  weight_optimizer: 
    name: SGD
    model_params_type: weight
    params: 
      lr: 0.01
      weight_decay: 0.0001
      momentum: 0.9
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 225270
  quant_optimizer: 
    name: SGD
    model_params_type: quant
    params: 
      lr: 0.01
      momentum: 0.9
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 225270

training_loop: &training_loop !TrainingLoop
  dataset: *dataset
  loss: !CrossEntropyLoss
  train_metrics:
    accuracy: !Accuracy
  val_metrics:
    accuracy: !Accuracy

task: !Task
  training_loop: *training_loop
  epochs: 90
  model_parser: *model_parser
  optimizers: *optimizers
  model_saver:
    monitor: "val_accuracy"
    mode: max
  callbacks:
    - !QuantImagesCallback
