model_parser: &model_parser !ModelParser
  wrappers:
    Conv2d: !QuantConv2d
      quantizer: !ModuleQuantizer
        input_quantizer: !StepOffsetQuantizer
          initializer: !MinErrorInitializer
        weight_quantizer: !StepQuantizer
          initializer: !MinErrorInitializer 
          per_channel: true

  input_bit_width:
    default: 2
    exceptions:
      conv1.0: 8
      conv3.0: 8
  weight_bit_width:
    default: 2
    exceptions:
      conv1.0: 8
      conv3.0: 8
  half_wave:
    default: true
    exceptions:
      conv1.0: false

# Dataset
dataset: &dataset !DIV2KDataloader
  batch_size: 32
  patch_size: 128
  scale: 4

# Optimizers
optimizers: &optimizers
  weight_optimizer: 
    name: Adam
    model_params_type: all
    params:
      lr: 0.001
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 180000

training_loop: &training_loop !TrainingLoop
  dataset: *dataset
  loss: !L1Loss
  train_metrics:
    PSNR: !PSNR
  val_metrics:
    PSNR: !PSNR

task: !Task
  training_loop: *training_loop
  epochs: 7200
  model_parser: *model_parser
  optimizers: *optimizers
  model_saver:
    monitor: "val_PSNR"
    mode: max
  check_val_every_n_epochs: 50
  callbacks:
    - !BenchmarkSuperresolutionCallback
      scale: 4
      psnr: !psnr
    - !QuantImagesCallback
