# Dataset
dataset: &dataset !ImageNet2012Dataloader
  batch_size: 512

# Optimizers
optimizers: &optimizers
  weight_optimizer: 
    name: SGD
    params: 
      lr: 0.1
      weight_decay: 0.0001
      momentum: 0.9
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 225270 # 2503 * 90

training_loop: &training_loop !TrainingLoop
  dataset: *dataset
  loss: !CrossEntropyLoss
  train_metrics:
    accuracy: !Accuracy
  val_metrics:
    accuracy: !Accuracy
  print_calibration: false

task: !Task
  training_loop: *training_loop
  epochs: 90
  optimizers: *optimizers
  model_arch: resnet18
  model_saver:
    monitor: "val_accuracy"
    mode: max
